version: '3.8'
services:
  seacinematix:
    image: ghcr.io/bagashiz/sea-cinema-tix:main
    container_name: seacinematix
    ports:
      - '8000:8000'
    env_file:
      - .env

# Nginx Proxy Manager Network (https://nginxproxymanager.com/)
# networks:
#   default:
#     external: true
#     name: nginx-network
